### ISSUE TITLE
compatibility with sphinx v3

### ISSUE THREAD

**Issue by superzazu** [boolangery/sphinx-luadomain#1]
Hello,

While trying this extension with sphinx v3.0.1, I encountered an error:

```
Running Sphinx v3.0.1

Extension error:
Could not import extension sphinxcontrib.luadomain (exception: cannot import name 'l_' from 'sphinx.locale' (/usr/local/lib/python3.7/site-packages/sphinx/locale/__init__.py))
```

Is it a problem on my end, or a compatibility problem with the new version of sphinx? I don't have the error with sphinx 2.4.4.

Thank you in advance.

**Comment by boolangery** [comment]
Hi, yes maybe this extension need to be updated. I will try to find some time for it

**Comment by boolangery** [comment]
Ok it was not a big deal, try with the 1.1.2

**Comment by superzazu** [comment]
That fixed the problem, thank you!
